const RECALL_SESSIONS = [
  {
    word: "Spoon",
    audio: "Rainbow",
    picture: "Apple",
    wordHint: "It is used to eat soup.",
    audioHint: "It is a colorful arch in the sky after rain.",
    pictureHint: "It is a red fruit that grows on trees.",
  },
  {
    word: "Bicycle",
    audio: "Shark",
    picture: "Pencil",
    wordHint: "It is a two-wheeled vehicle used for transportation.",
    audioHint: "It is a dangerous predator that swims in the ocean.",
    pictureHint: "It is a tool used for writing or drawing.",
  },
  {
    word: "Castle",
    audio: "Notebook",
    picture: "Volcano",
    wordHint: "It is a large building where royalty lives.",
    audioHint: "It is a book used for writing notes.",
    pictureHint: "It is a mountain that erupts hot lava.",
  },
  {
    word: "Clock",
    audio: "Globe",
    picture: "Hammer",
    wordHint: "It is a device that tells the time.",
    audioHint: "It is a model of the Earth.",
    pictureHint: "It is a tool used to drive nails into surfaces.",
  },
  {
    word: "Crown",
    audio: "Pineapple",
    picture: "Lamp",
    wordHint: "It is a decorative headpiece worn by kings and queens.",
    audioHint: "It is a tropical fruit with a spiky exterior.",
    pictureHint: "It is a device that provides light in a room.",
  },
  {
    word: "Flower",
    audio: "Hammock",
    picture: "Kite",
    wordHint: "It is a colorful plant that blooms from a stem.",
    audioHint: "It is a hanging bed made of fabric or rope.",
    pictureHint: "It is a toy that flies in the sky when there is wind.",
  },
  {
    word: "Window",
    audio: "Grass",
    picture: "Moon",
    wordHint: "It is a glass opening in a wall or door.",
    audioHint: "It is the green plant that covers lawns.",
    pictureHint: "It is the natural satellite that orbits Earth.",
  },
  {
    word: "Fire",
    audio: "Leaf",
    picture: "Key",
    wordHint: "It is a hot, glowing mass that produces heat and light.",
    audioHint: "It is a flat green part of a plant or tree.",
    pictureHint: "It is a metal object used to unlock doors.",
  },
  {
    word: "Cookie",
    audio: "Door",
    picture: "Knife",
    wordHint: "It is a sweet baked treat made with flour and sugar.",
    audioHint: "It is an entrance to a room or building.",
    pictureHint: "It is a tool with a sharp edge used for cutting.",
  },
  {
    word: "Rain",
    audio: "Egg",
    picture: "Star",
    wordHint: "It is water that falls from clouds in the sky.",
    audioHint: "It is an oval-shaped food that comes from birds.",
    pictureHint: "It is a bright celestial object visible in the night sky.",
  },
  {
    word: "Locket",
    audio: "Cloud",
    picture: "ladder",
    wordHint: "It is a small pendant that opens to hold a picture.",
    audioHint: "It is a white or gray mass floating in the sky.",
    pictureHint: "It is a structure with rungs used for climbing.",
  },
  {
    word: "Bottle",
    audio: "Ruler",
    picture: "Button",
    wordHint: "It is a container with a narrow neck used to hold liquids.",
    audioHint: "It is a tool used to measure length or draw straight lines.",
    pictureHint: "It is a small disc used to fasten clothing.",
  },
  {
    word: "Toothbrush",
    audio: "Kettle",
    picture: "Candle",
    wordHint: "It is a brush used to clean teeth.",
    audioHint: "It is a vessel used to boil water, often for tea.",
    pictureHint: "It is a cylinder of wax with a wick that produces light when lit.",
  },
  {
    word: "Drum",
    audio: "Brush",
    picture: "Carrot",
    wordHint: "It is a musical instrument that makes sound when beaten.",
    audioHint: "It is a tool with bristles used for cleaning or painting.",
    pictureHint: "It is an orange vegetable that grows underground.",
  },
  {
    word: "Rope",
    audio: "Lemon",
    picture: "Bell",
    wordHint: "It is a thick cord made by twisting fibers together.",
    audioHint: "It is a yellow citrus fruit with sour juice.",
    pictureHint: "It is a metal object that makes a ringing sound when struck.",
  },
  {
    word: "Belt",
    audio: "Alarm",
    picture: "Chair",
    wordHint: "It is a strip worn around the waist to hold up clothing.",
    audioHint: "It is a device that makes a loud sound to wake you up.",
    pictureHint: "It is a piece of furniture designed for sitting.",
  },
  {
    word: "Wheel",
    audio: "Block",
    picture: "Vase",
    wordHint: "It is a circular object that rotates to allow movement.",
    audioHint: "It is a solid piece of material, often cube-shaped.",
    pictureHint: "It is a decorative container used to hold flowers.",
  },
  {
    word: "Bridge",
    audio: "Mouse",
    picture: "Sock",
    wordHint: "It is a structure built to span a physical obstacle.",
    audioHint: "It is a small rodent with a long tail.",
    pictureHint: "It is a piece of clothing worn on the feet.",
  },
  {
    word: "Honey",
    audio: "Frame",
    picture: "Fan",
    wordHint: "It is a sweet, sticky substance made by bees.",
    audioHint: "It is a border that surrounds and supports a picture.",
    pictureHint: "It is a device that circulates air to cool a room.",
  },
  {
    word: "Glass",
    audio: "Boat",
    picture: "Bowl",
    wordHint: "It is a transparent material made from sand.",
    audioHint: "It is a vessel that travels on water.",
    pictureHint: "It is a round container used for holding food.",
  },
  {
    word: "Basket",
    audio: "Salt",
    picture: "Map",
    wordHint: "It is a container made of woven materials for holding items.",
    audioHint: "It is a mineral used to enhance the flavor of food.",
    pictureHint: "It is a representation of an area showing physical features.",
  },
];

export default RECALL_SESSIONS;
