name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.5

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm install
        working-directory: react_frontend
        
      - name: Install missing Babel plugin
        run: npm install @babel/plugin-proposal-private-property-in-object
        working-directory: react_frontend

      - name: Run all tests
        run: npm test -- --testPathPattern=src/__tests__/ --watchAll=false
        working-directory: react_frontend
